# Generated by Django 5.2.2 on 2025-06-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=150)),
                ('temporada', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('Nacional', 'Nacional'), ('Autonómico', 'Autonómico'), ('Internacional', 'Internacional')], max_length=20)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
            },
        ),
        migrations.AlterModelOptions(
            name='tirador',
            options={'verbose_name': 'Tirador', 'verbose_name_plural': 'Tiradores'},
        ),
    ]
