# Generated by Django 5.2.2 on 2025-06-05 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0004_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirador',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultados.categoria'),
        ),
    ]
