# Generated by Django 5.2.2 on 2025-06-05 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0007_tirador_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('federacion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
            },
        ),
        migrations.AlterField(
            model_name='equipo',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultados.club'),
        ),
        migrations.AlterField(
            model_name='tirador',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultados.club'),
        ),
    ]
