# Generated by Django 5.2.2 on 2025-06-05 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0008_club_alter_equipo_club_alter_tirador_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Federacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ambito', models.CharField(choices=[('Autonómica', 'Autonómica'), ('Nacional', 'Nacional'), ('Internacional', 'Internacional')], max_length=50)),
                ('pais', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Federación',
                'verbose_name_plural': 'Federaciones',
            },
        ),
        migrations.AlterField(
            model_name='club',
            name='federacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultados.federacion'),
        ),
    ]
