# Generated by Django 5.2.2 on 2025-06-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0009_federacion_alter_club_federacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campeonato',
            name='lugar',
        ),
        migrations.AddField(
            model_name='campeonato',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resultados.club'),
        ),
    ]
