# Generated by Django 5.2.2 on 2025-06-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0010_remove_campeonato_lugar_campeonato_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='posicion',
        ),
    ]
