# Generated by Django 5.2.2 on 2025-06-05 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0011_remove_resultado_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.PositiveIntegerField(help_text='Orden en el circuito')),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.PositiveIntegerField(help_text='Número de paseo del tirador por las canchas')),
                ('helice_1', models.BooleanField(verbose_name='Hélice 1 (acierto)')),
                ('helice_2', models.BooleanField(verbose_name='Hélice 2 (acierto)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados.campeonato')),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados.cancha')),
                ('tirador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados.tirador')),
            ],
            options={
                'verbose_name': 'Tiro',
                'verbose_name_plural': 'Tiros',
                'ordering': ['campeonato', 'ronda', 'cancha__orden'],
            },
        ),
    ]
